BOARD_W = 5
BOARD_H = 6
FILES = "abcde"

WHITE = 0
BLACK = 1

PIECE_NONE   = 0
PIECE_PAWN   = 1
PIECE_KNIGHT = 2
PIECE_BISHOP = 3
PIECE_ROOK   = 4
PIECE_QUEEN  = 5
PIECE_KING   = 6

PIECE_SYMBOL = {
    (WHITE, PIECE_PAWN): "P", (BLACK, PIECE_PAWN): "p",
    (WHITE, PIECE_KNIGHT): "N", (BLACK, PIECE_KNIGHT): "n",
    (WHITE, PIECE_BISHOP): "B", (BLACK, PIECE_BISHOP): "b",
    (WHITE, PIECE_QUEEN): "Q", (BLACK, PIECE_QUEEN): "q",
    (WHITE, PIECE_KING): "K", (BLACK, PIECE_KING): "k",
    (WHITE, PIECE_ROOK): "R", (BLACK, PIECE_ROOK): "r",
}
